// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV82iE23Zcz5f-Jit6VtBpShQq5cqR1yw',
    appId: '1:467449712814:web:df48903d65242f7b401d3f',
    messagingSenderId: '467449712814',
    projectId: 'impersonation-detector',
    authDomain: 'impersonation-detector.firebaseapp.com',
    storageBucket: 'impersonation-detector.appspot.com',
    measurementId: 'G-V7L2RJ8FW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvOirMoSs5Pf03kmSrKBH8HVOzc9AItxM',
    appId: '1:467449712814:android:69807341ff8e272f401d3f',
    messagingSenderId: '467449712814',
    projectId: 'impersonation-detector',
    storageBucket: 'impersonation-detector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa7UEP9c5jArSA6kqyzywZlzAwjBNK-Qw',
    appId: '1:467449712814:ios:948af38d1e256b11401d3f',
    messagingSenderId: '467449712814',
    projectId: 'impersonation-detector',
    storageBucket: 'impersonation-detector.appspot.com',
    iosBundleId: 'com.example.impersonationDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa7UEP9c5jArSA6kqyzywZlzAwjBNK-Qw',
    appId: '1:467449712814:ios:c1ee46776211702e401d3f',
    messagingSenderId: '467449712814',
    projectId: 'impersonation-detector',
    storageBucket: 'impersonation-detector.appspot.com',
    iosBundleId: 'com.example.impersonationDetector.RunnerTests',
  );
}
